services:
  momo.eveapi:
    image: momo.eveapi
    build:
      context: .
      dockerfile: Execution/MoMo.EveApi/Dockerfile

  momo.adamapi:
    image: momo.adamapi
    build:
      context: .
      dockerfile: Execution/MoMo.AdamApi/Dockerfile
