services:
  momo.adamapi:
    image: momo.adamapi
    build:
      context: .
      dockerfile: MoMo.AdamApi/Dockerfile

  momo.eveapi:
    image: momo.eveapi
    build:
      context: .
      dockerfile: MoMo.EveApi/Dockerfile
